# ============================================================
#   CONFIG.PY — كل اعدادات العميل هنا فقط
#   عدل هذا الملف لكل عميل جديد، لا تلمس باقي الكود
# ============================================================

RESTAURANT_NAME = "FlameGrill"
RESTAURANT_SLOGAN = "Fast Food Algerien"
RESTAURANT_HERO = "Goutez la Flamme Authentique"
RESTAURANT_DESC = "Pizza croustillante, Tacos genereux, Burgers juteux"

PRIMARY_COLOR = "#ff5e14"
SECONDARY_COLOR = "#ff8c42"

TELEGRAM_TOKEN = "8708650898:AAFUKwQRo04xeKUptXQf-mEm_W2LmSkAVbU"
TELEGRAM_CHAT_ID = "5274379305"

DEVELOPER_NAME = "odil"

MENU = [
    {
        "id": 1,
        "name": "Tacos Poulet",
        "price": 400,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos au poulet grille",
    },
    {
        "id": 2,
        "name": "Tacos Mexicain",
        "price": 400,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos mexicain epice",
    },
    {
        "id": 3,
        "name": "Tacos Kabda",
        "price": 450,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos au foie",
    },
    {
        "id": 4,
        "name": "Tacos Chawarma",
        "price": 400,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos chawarma",
    },
    {
        "id": 5,
        "name": "Tacos Viande",
        "price": 450,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos a la viande",
    },
    {
        "id": 6,
        "name": "Tacos Mixte",
        "price": 500,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos mixte",
    },
    {
        "id": 7,
        "name": "Tacos Crispy",
        "price": 600,
        "category": "Tacos",
        "emoji": "🌮",
        "desc": "Tacos crispy",
    },
    {
        "id": 8,
        "name": "Calzoni Poulet",
        "price": 450,
        "category": "Calzoni",
        "emoji": "🫓",
        "desc": "Calzoni au poulet",
    },
    {
        "id": 9,
        "name": "Calzoni Viande",
        "price": 550,
        "category": "Calzoni",
        "emoji": "🫓",
        "desc": "Calzoni a la viande",
    },
    {
        "id": 10,
        "name": "Calzoni Kbda",
        "price": 500,
        "category": "Calzoni",
        "emoji": "🫓",
        "desc": "Calzoni au foie",
    },
    {
        "id": 11,
        "name": "Makloub Poulet",
        "price": 350,
        "category": "Makloub",
        "emoji": "🥙",
        "desc": "Makloub au poulet",
    },
    {
        "id": 12,
        "name": "Makloub Viande",
        "price": 400,
        "category": "Makloub",
        "emoji": "🥙",
        "desc": "Makloub a la viande",
    },
    {
        "id": 13,
        "name": "Grec Poulet",
        "price": 400,
        "category": "Grec",
        "emoji": "🥗",
        "desc": "Grec au poulet",
    },
    {
        "id": 14,
        "name": "Grec Viande",
        "price": 450,
        "category": "Grec",
        "emoji": "🥗",
        "desc": "Grec a la viande",
    },
    {
        "id": 15,
        "name": "Malfouf Poulet",
        "price": 400,
        "category": "Malfouf",
        "emoji": "🌯",
        "desc": "Malfouf au poulet",
    },
    {
        "id": 16,
        "name": "Malfouf Viande",
        "price": 450,
        "category": "Malfouf",
        "emoji": "🌯",
        "desc": "Malfouf a la viande",
    },
    {
        "id": 17,
        "name": "Pizza Poulet",
        "price": 400,
        "category": "Pizza",
        "emoji": "🍕",
        "desc": "Pizza au poulet",
    },
    {
        "id": 18,
        "name": "Pizza Marguerite",
        "price": 250,
        "category": "Pizza",
        "emoji": "🍕",
        "desc": "Pizza marguerite",
    },
    {
        "id": 19,
        "name": "Pizza Viande",
        "price": 500,
        "category": "Pizza",
        "emoji": "🍕",
        "desc": "Pizza a la viande",
    },
    {
        "id": 20,
        "name": "Pizza 4 Fromages",
        "price": 600,
        "category": "Pizza",
        "emoji": "🍕",
        "desc": "Pizza 4 fromages",
    },
    {
        "id": 21,
        "name": "Pizza Chef",
        "price": 650,
        "category": "Pizza",
        "emoji": "🍕",
        "desc": "Pizza speciale chef",
    },
    {
        "id": 22,
        "name": "Cheese Burger",
        "price": 450,
        "category": "Burger",
        "emoji": "🍔",
        "desc": "Cheese burger classique",
    },
    {
        "id": 23,
        "name": "Double Cheese Burger",
        "price": 550,
        "category": "Burger",
        "emoji": "🍔",
        "desc": "Double cheese burger",
    },
    {
        "id": 24,
        "name": "Chicken Burger",
        "price": 450,
        "category": "Burger",
        "emoji": "🍔",
        "desc": "Burger au poulet",
    },
    {
        "id": 25,
        "name": "Plat Chawarma",
        "price": 600,
        "category": "Plats",
        "emoji": "🍽️",
        "desc": "Plat chawarma complet",
    },
    {
        "id": 26,
        "name": "Plat Chef 1 Personne",
        "price": 1200,
        "category": "Plats",
        "emoji": "🍽️",
        "desc": "Plat de chef 1 personne",
    },
    {
        "id": 27,
        "name": "Plat Chef 2 Personnes",
        "price": 1900,
        "category": "Plats",
        "emoji": "🍽️",
        "desc": "Plat de chef 2 personnes",
    },
    {
        "id": 28,
        "name": "Gratin Poulet",
        "price": 400,
        "category": "Gratin",
        "emoji": "🥘",
        "desc": "Gratin au poulet",
    },
    {
        "id": 29,
        "name": "Gratin Viande",
        "price": 500,
        "category": "Gratin",
        "emoji": "🥘",
        "desc": "Gratin a la viande",
    },
    {
        "id": 30,
        "name": "Tiramisu",
        "price": 450,
        "category": "Desserts",
        "emoji": "🍰",
        "desc": "Tiramisu maison",
    },
    {
        "id": 31,
        "name": "Cheese Cake",
        "price": 400,
        "category": "Desserts",
        "emoji": "🍰",
        "desc": "Cheese cake",
    },
    {
        "id": 32,
        "name": "Creme Brulee",
        "price": 300,
        "category": "Desserts",
        "emoji": "🍮",
        "desc": "Creme brulee maison",
    },
]
